/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marquiz.admin;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import marquiz.userHome;

/**
 *
 * @author Madluke
 */
public class adminHome extends javax.swing.JFrame {
  public static int open = 0;

    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddT = new javax.swing.JButton();
        btnEditT = new javax.swing.JButton();
        btnDelT = new javax.swing.JButton();
        btnPengT = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        btnLihatT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 249, 255));

        btnAddT.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        btnAddT.setText("tambah teacher");
        btnAddT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTActionPerformed(evt);
            }
        });

        btnEditT.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        btnEditT.setText("edit teacher");
        btnEditT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTActionPerformed(evt);
            }
        });

        btnDelT.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        btnDelT.setText("hapus teacher");
        btnDelT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelTActionPerformed(evt);
            }
        });

        btnPengT.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        btnPengT.setText("pengaturan");
        btnPengT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengTActionPerformed(evt);
            }
        });

        btnSignOut.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        btnSignOut.setText("keluar");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        btnLihatT.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        btnLihatT.setText("lihat teacher");
        btnLihatT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnEditT)
                    .addComponent(btnDelT)
                    .addComponent(btnPengT)
                    .addComponent(btnLihatT)
                    .addComponent(btnAddT))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAddT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditT)
                .addGap(12, 12, 12)
                .addComponent(btnDelT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLihatT)
                .addGap(18, 18, 18)
                .addComponent(btnPengT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int response;
        response = JOptionPane.showConfirmDialog(jf, "Do you really want to Logout?", "Select", JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){
            userHome page = new userHome();
            page.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnAddTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTActionPerformed
        // TODO add your handling code here:       
        if (open == 0){
            new TambahTeacher().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
      
    }//GEN-LAST:event_btnAddTActionPerformed

    private void btnEditTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTActionPerformed
        // TODO add your handling code here:
        if (open == 0){
            new EditTeacher().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
        
    }//GEN-LAST:event_btnEditTActionPerformed

    private void btnDelTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelTActionPerformed
        // TODO add your handling code here:
        if (open == 0){
            new HapusTeacher().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
    }//GEN-LAST:event_btnDelTActionPerformed

    private void btnPengTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengTActionPerformed
        // TODO add your handling code here:
        if (open == 0){
            new Pengaturan().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
    }//GEN-LAST:event_btnPengTActionPerformed

    private void btnLihatTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatTActionPerformed
        // TODO add your handling code here:
        if (open == 0){
            new listTeacher().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
    }//GEN-LAST:event_btnLihatTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddT;
    private javax.swing.JButton btnDelT;
    private javax.swing.JButton btnEditT;
    private javax.swing.JButton btnLihatT;
    private javax.swing.JButton btnPengT;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
