/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marquiz.teacher;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import marquiz.userHome;

/**
 *
 * @author Madluke
 */
public class teacherHome extends javax.swing.JFrame {
  public static int open = 0;

    /**
     * Creates new form teacherHome
     */
    public teacherHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambahSoal = new javax.swing.JButton();
        btnEditSoal = new javax.swing.JButton();
        btnDelSoal = new javax.swing.JButton();
        btnListSoal = new javax.swing.JButton();
        btnListTestTaker = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTambahSoal.setText("tambah soal");
        btnTambahSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSoalActionPerformed(evt);
            }
        });

        btnEditSoal.setText("update soal");
        btnEditSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSoalActionPerformed(evt);
            }
        });

        btnDelSoal.setText("hapus soal");
        btnDelSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSoalActionPerformed(evt);
            }
        });

        btnListSoal.setText("lihat semua soal");
        btnListSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListSoalActionPerformed(evt);
            }
        });

        btnListTestTaker.setText("lihat test taker");
        btnListTestTaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListTestTakerActionPerformed(evt);
            }
        });

        btnSignOut.setText("keluar");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        btnKembali.setText("kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnTambahSoal)
                    .addComponent(btnEditSoal)
                    .addComponent(btnDelSoal)
                    .addComponent(btnListSoal)
                    .addComponent(btnListTestTaker))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(18, 18, 18)
                .addComponent(btnSignOut)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnTambahSoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditSoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelSoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListSoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListTestTaker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignOut)
                    .addComponent(btnKembali))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSoalActionPerformed
        if (open == 0){
            new TambahSoal().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
    }//GEN-LAST:event_btnTambahSoalActionPerformed

    private void btnEditSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSoalActionPerformed
        if (open == 0){
            new EditSoal().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
    }//GEN-LAST:event_btnEditSoalActionPerformed

    private void btnDelSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSoalActionPerformed
        if (open == 0){
            new HapusSoal().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
    }//GEN-LAST:event_btnDelSoalActionPerformed

    private void btnListSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListSoalActionPerformed
        // TODO add your handling code here:
        if (open == 0){
            new listSoal().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
        
    }//GEN-LAST:event_btnListSoalActionPerformed

    private void btnListTestTakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListTestTakerActionPerformed
        // TODO add your handling code here:
        if (open == 0){
            new ListTestTaker().setVisible(true);
            open = 1;
        }else {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Form yang lain masih dibuka");
        }
    }//GEN-LAST:event_btnListTestTakerActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        LoginTeacher page = new LoginTeacher();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int response;
        response = JOptionPane.showConfirmDialog(jf, "Do you really want to Logout?", "Select", JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){
            userHome page = new userHome();
            page.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelSoal;
    private javax.swing.JButton btnEditSoal;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnListSoal;
    private javax.swing.JButton btnListTestTaker;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnTambahSoal;
    // End of variables declaration//GEN-END:variables
}
